language: node_js
node_js:
  - "0.10"

install:
  - npm install
  # Install Screener CI Script
  - wget https://s3-us-west-2.amazonaws.com/screener-files/ci/v2/screener-ci.zip
  - unzip screener-ci.zip
  # Install Screener Tunnel Client
  - wget https://s3-us-west-2.amazonaws.com/screener-files/screener-tunnel/screener-tunnel-client-linux-amd64.zip
  - unzip screener-tunnel-client-linux-amd64.zip

script:
  # get current branch (why?: https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/)
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  # start tunnel
  - ./screener-tunnel-client -apikey="$SCREENER_API_KEY" -host="$BRANCH.127.0.0.1.xip.io:8080" &
  # start server
  - npm start &
  # run tests
  - npm test
  - ./screener-ci.sh $SCREENER_API_KEY $SCREENER_GROUP_ID $TRAVIS_BUILD_NUMBER
